name: nazoratchi_mobile
description: "Nazoratchi - Qo'qon MTU Safety Oversight Mobile App"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  http: ^1.0.0
  provider: ^6.0.0
  shared_preferences: ^2.1.0
  intl: ^0.19.0
  flutter_local_notifications: ^16.0.0
  firebase_messaging: ^14.6.0
  image_picker: ^1.0.0
  geolocator: ^9.0.0
  permission_handler: ^11.4.0
  flutter_spinkit: ^5.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_linter: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
